app:
  port: ':3000'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2019-09-15T14:04:05'

producer:
  brokers: ['localhost:9092']
  topic: 'store.municipality.superhero'
  batch_size: 1
  batch_timeout: 10